#requires -Version 5.1
[CmdletBinding()]
param([ValidateSet('Fixture','LiveObservation')][string]$Mode='Fixture',[string]$FixturePath,[string]$OutputDirectory='E:\!Chrome_Downloads\PNCC-STABLE-CREDENTIAL-HOSTKEY-V4')
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$ExpectedEngineSha='843c006b896607da19406998b54d4e6897fa8eb62d3e6bc92cc77255fe4833cf'
$StateDir=Join-Path $env:LOCALAPPDATA 'VPS-Control-v6.3';$PidFile=Join-Path $StateDir 'watchdog.pid';$Heartbeat=Join-Path $StateDir 'watchdog-heartbeat.json'
$RepoRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ManagerPath=Join-Path $RepoRoot 'src\windows-v7\VPS-Control-v7-tunnel-manager.ps1'
function WJ($v,[string]$p){$d=Split-Path -Parent $p;if($d){New-Item -ItemType Directory -Force -Path $d|Out-Null};[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 16),(New-Object Text.UTF8Encoding($true)))}
function P([int]$id){try{Get-CimInstance Win32_Process -Filter ('ProcessId='+$id) -ErrorAction Stop}catch{$null}}
function F([string]$c){if(-not$c){return ''};$m=[regex]::Match($c,'(?i)(?:^|\s)-File\s+(?:"([^"]+)"|''([^'']+)''|(\S+))');if(-not$m.Success){return ''};foreach($i in 1..3){if($m.Groups[$i].Success){return [string]$m.Groups[$i].Value}};''}
function S([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Snap([int]$port){$r=@(Get-NetTCPConnection -State Listen -LocalAddress '127.0.0.1' -LocalPort $port -ErrorAction SilentlyContinue);[ordered]@{port=$port;listening=($r.Count-gt0);listener_count=$r.Count;owner_pids=@($r|%{[int]$_.OwningProcess}|sort)}}
function K($v){$v|ConvertTo-Json -Depth 8 -Compress}
function Test-CanonicalOrder([string]$Raw){$startMarker="if(`$Action-eq'StartReserve'){";$start=$Raw.IndexOf($startMarker);if($start-lt0){return $false};$h=$Raw.IndexOf('Ensure-V7OfficialPuttyHostKeyTrust',$start);$g=$Raw.IndexOf('if(-not $hostKeyTrustOk)',$h);$d=$Raw.IndexOf('Get-DpapiPassword',$h);$a=$Raw.IndexOf("`$args=@('-ssh'",$d);return($h-gt$start-and$g-gt$h-and$d-gt$g-and$a-gt$d)}
function Test-CanonicalDpapi([string]$Raw){$f=$Raw.IndexOf('function Get-DpapiPassword');if($f-lt0){return $false};$tail=$Raw.Substring($f,[Math]::Min(2200,$Raw.Length-$f));return($tail-match"secrets\\vps\\'.*?\.dpapi" -or $tail-match"secrets\\vps\\") -and $tail-match'ConvertTo-SecureString\s+-String\s+\$cipher' -and $tail-match'SecureStringToBSTR' -and $tail-match'ZeroFreeBSTR'}
New-Item -ItemType Directory -Force -Path $OutputDirectory|Out-Null;$rp=Join-Path $OutputDirectory 'stable-credential-hostkey-v4-result.json'
if($Mode-ceq'Fixture'){$f=Get-Content -LiteralPath $FixturePath -Raw -Encoding UTF8|ConvertFrom-Json;$checks=[ordered]@{live_exact_engine_identity=[bool]$f.live_exact_engine_identity;canonical_source_order=[bool]$f.canonical_source_order;canonical_dpapi_implementation=[bool]$f.canonical_dpapi_implementation;pwfile_only=[bool]$f.pwfile_only;plaintext_pw_forbidden=[bool]$f.plaintext_pw_forbidden;hostkey_fail_closed=[bool]$f.hostkey_fail_closed;reserve_1080_untouched=[bool]$f.reserve_1080_untouched;primary_1081_observation_only=[bool]$f.primary_1081_observation_only;runtime_authority_false=[bool]$f.runtime_authority_false;promotion_eligible_false=[bool]$f.promotion_eligible_false};$bad=@($checks.GetEnumerator()|?{-not[bool]$_.Value}|%{$_.Key});$ok=($bad.Count-eq0);$r=[ordered]@{schema_version=4;contract_id='PNCC_STABLE_CREDENTIAL_HOSTKEY_V4';mode='Fixture';state=$(if($ok){'CREDENTIAL_HOSTKEY_V4_CONTRACT_ADMITTED'}else{'BLOCKED'});checks=$checks;failed_checks=$bad;runtime_mutation=$false;runtime_authority=$false;promotion_eligible=$false};WJ $r $rp;Write-Output ('PNCC_STABLE_CREDENTIAL_HOSTKEY_V4='+$r.state+' RUNTIME_MUTATION=false RUNTIME_AUTHORITY=false PROMOTION_ELIGIBLE=false');if($ok){exit 0}else{exit 50}}
if($env:OS-cne'Windows_NT'){throw 'LiveObservation requires Windows'}
$b1080=Snap 1080;$b1081=Snap 1081;if(-not$b1080.listening-or-not$b1081.listening){throw '1080/1081 listener baseline missing'}
if(-not(Test-Path -LiteralPath $PidFile)){throw 'watchdog pid missing'};$wid=[int](Get-Content -LiteralPath $PidFile -Raw).Trim();$wp=P $wid;if($null-eq$wp){throw 'watchdog missing'};$wc=[string]$wp.CommandLine;if($wc-notmatch'(?i)(?:^|\s)-Action\s+Watchdog(?:\s|$)'){throw 'watchdog action mismatch'};$ef=F $wc;if(-not$ef-or(S $ef)-cne$ExpectedEngineSha){throw 'watchdog engine mismatch'}
$hb=Get-Content -LiteralPath $Heartbeat -Raw|ConvertFrom-Json;$age=[int][math]::Round(((Get-Date)-([datetime]$hb.Timestamp)).TotalSeconds);if([int]$hb.Pid-ne$wid-or$age-lt0-or$age-gt240){throw 'heartbeat binding/freshness failed'}
$rows=@(Get-NetTCPConnection -State Listen -LocalAddress '127.0.0.1' -LocalPort 1081 -ErrorAction Stop);if($rows.Count-ne1){throw 'expected one 1081 listener'};$tp=P ([int]$rows[0].OwningProcess);$tc=[string]$tp.CommandLine;if([string]$tp.Name-notmatch'(?i)^(putty|putty_portable|plink)\.exe$'){throw '1081 owner not PuTTY-family'};if($tc-notmatch'(?i)(?:^|\s)-pwfile(?:\s|=)'){throw '1081 -pwfile missing'};if($tc-match'(?i)(?:^|\s)-pw(?:\s|=)'){throw 'plaintext -pw observed'}
if(-not(Test-Path -LiteralPath $ManagerPath -PathType Leaf)){throw 'canonical tunnel manager missing'};$mraw=[IO.File]::ReadAllText($ManagerPath);if(($mraw-match'(?i)-hostkey\s+\*')-or($mraw-match'(?i)auto.?accept.*host.?key')-or($mraw-match'(?i)HostKeyVerificationDisableAllowed\s*=\s*\$true')){throw 'hostkey bypass marker observed'};if(-not(Test-CanonicalOrder $mraw)){throw 'canonical hostkey guard/decrypt/args order not proven'};if(-not(Test-CanonicalDpapi $mraw)){throw 'canonical DPAPI implementation not proven'}
$a1080=Snap 1080;$a1081=Snap 1081;if((K $b1080)-cne(K $a1080)){throw '1080 changed'};if((K $b1081)-cne(K $a1081)){throw '1081 changed'}
$r=[ordered]@{schema_version=4;contract_id='PNCC_STABLE_CREDENTIAL_HOSTKEY_V4';mode='LiveObservation';state='CREDENTIAL_HOSTKEY_V4_PASS';exact_engine_sha256=$ExpectedEngineSha;live_exact_engine_identity=$true;canonical_source_order=$true;canonical_dpapi_implementation=$true;pwfile_only=$true;plaintext_pw=$false;hostkey_fail_closed_source_contract=$true;reserve_1080_unchanged=$true;primary_1081_unchanged=$true;runtime_mutation=$false;runtime_authority=$false;promotion_eligible=$false};WJ $r $rp;Write-Output 'PNCC_STABLE_CREDENTIAL_HOSTKEY_V4=CREDENTIAL_HOSTKEY_V4_PASS RUNTIME_MUTATION=false RUNTIME_AUTHORITY=false PROMOTION_ELIGIBLE=false';Write-Output ('RESULT='+$rp);exit 0
